# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-27 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('subtopic', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('set_number', models.CharField(max_length=4)),
                ('date_written', models.DateTimeField(auto_now_add=True, verbose_name=b'date created')),
                ('date_last_mod', models.DateTimeField(auto_now_add=True, verbose_name=b'date last modified')),
                ('question_type', models.CharField(max_length=20)),
                ('question_text', models.CharField(max_length=10000)),
                ('short_answer_answer_text', models.CharField(max_length=10000)),
                ('w', models.CharField(max_length=100)),
                ('x', models.CharField(max_length=100)),
                ('y', models.CharField(max_length=100)),
                ('z', models.CharField(max_length=100)),
                ('correct', models.CharField(max_length=1)),
                ('difficulty', models.IntegerField()),
            ],
        ),
    ]
