# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-06 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20161127_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
