# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-09 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_auto_20161208_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tossup_or_bonus',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
