# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-09 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_auto_20161208_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='comp',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
